language: node_js
node_js:
  - "5.5"
services:
  - redis-server
addons:
  code_climate:
    repo_token: 32da99c3de32f82a5d5916047ed80cc1449de75837044f066a70a1c7a7de1941
after_script:
  - codeclimate-test-reporter < coverage/lcov.info
